services:
  notes_api:
    container_name: notes_api
    build:
      context: ./
      dockerfile: ./cmd/api/Dockerfile
    env_file:
      - .env
    ports:
      - $API_PORT:$API_PORT
    volumes:
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
      - ./cmd/api/:/app/cmd/api/
      - ./internal/:/app/internal/
    depends_on:
      notes_db:
        condition: service_healthy

  notes_db:
    image: postgres:16.0-alpine3.17
    container_name: notes_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./scripts/db_init.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - notes-db-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 2s

  migrate:
    image: migrate/migrate:v4.16.2
    container_name: notes_migrations
    depends_on:
      notes_db:
        condition: service_healthy
    volumes:
      - ./sql/migrations:/migrations
    command: >
      -path=./migrations/
      -database=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@notes_db:$POSTGRES_PORT/$POSTGRES_DB?sslmode=disable
      ${CMD:-up}

volumes:
  notes-db-data:
    driver: local
